import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getUrlWithScheme } from "@/lib/getUrlWithScheme";
import { headers } from "next/headers";
import CacheInitializer from "@/components/CacheInitializer";

// Configure Inter font with fallbacks and error handling
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  fallback: [
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Roboto",
    "Helvetica Neue",
    "Arial",
    "sans-serif",
  ],
  adjustFontFallback: true,
  preload: true,
});

export const metadata: Metadata = {
  title: "krallaser",
  description: "Generated by create next app",
  icons: {
    icon: "/whatsapp-icon.svg",
    shortcut: "/whatsapp-icon.svg",
    apple: "/whatsapp-icon.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const Headers = await headers();
  const host = Headers.get("host");
  if (!host) {
    throw new Error("Host header is missing or invalid");
  }

  const fullStoreUrl = getUrlWithScheme(host);
  
  try {
    const response = await fetch(`${fullStoreUrl}/api/fetchStore`, {
      cache: 'no-store' // Ensure fresh data on each request
    });
    
    if (!response.ok) {
      throw new Error(`Failed to fetch store data: ${response.status}`);
    }
    
    const data = await response.json();
    const storeData = data?.store?.stores?.[0];
    const itemsData = data?.items;
    
    console.log("Store data from ERPNext:", storeData);
    console.log("Items data from ERPNext:", itemsData);
    
    return (
      <html lang="en">
        <head>
          <title>{storeData?.store_name || "krallaser"}</title>
          <meta
            name="description"
            content={
              storeData?.store_detail?.tagline || "Generated by create next app"
            }
          />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/whatsapp-icon.svg" type="image/svg+xml" />
          <link rel="shortcut icon" href="/whatsapp-icon.svg" type="image/svg+xml" />
          <link rel="apple-touch-icon" href="/whatsapp-icon.svg" />
          {/* Preconnect to Google Fonts for faster loading */}
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="anonymous"
          />
          <style>
            {`
              :root {
                --primary-color: #EF4444;
                --secondary-color: #374151;
              }
            `}
          </style>
        </head>
        <body className={inter.className} cz-shortcut-listen="true">
          <CacheInitializer />
          {children}
        </body>
      </html>
    );
  } catch (error) {
    console.error("Error in layout:", error);
    
    // Fallback layout in case of error
    return (
      <html lang="en">
        <head>
          <title>krallaser</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/whatsapp-icon.svg" type="image/svg+xml" />
          <link rel="shortcut icon" href="/whatsapp-icon.svg" type="image/svg+xml" />
          <link rel="apple-touch-icon" href="/whatsapp-icon.svg" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="anonymous"
          />
        </head>
        <body className={inter.className} cz-shortcut-listen="true">
          <CacheInitializer />
          {children}
        </body>
      </html>
    );
  }
}
